##version: '3.3'
##
##services:
##  #service 1: definition of mysql database
##  db:
##    image: mysql:latest
##    networks:
##      - fort-networks
##    container_name: mysql-db2
##    environment:
##      - MYSQL_USER=root
##    ports:
##      - "3306:3306"
##    restart: always
##
##
##  #service 2: definition of phpMyAdmin
##  phpmyadmin:
##    image: phpmyadmin/phpmyadmin:latest
##    networks:
##      - fort-networks
##    container_name: my-phpmyadmin
##    ports:
##      - "8083:80"
##    restart: always
##
##    depends_on:
##      - db
##    environment:
##      SPRING_DATASOURCE_USERNAME: root
#
#
##service 3: definition of your spring-boot app
##  customerservice:                        #it is just a name, which will be used only in this file.
##    image: Fort-backand-app
##    networks:
##      - employee-mysql #name of the image after dockerfile executes
##    container_name: Fort-backand-app  #name of the container created from docker image
##    build:
##      context: .                        #docker file path (. means root directory)
##      dockerfile: dockerfile             #docker file name
##    ports:
##      - "8084:8084"                       #docker containter port with your os port
##    restart: always
##
##    depends_on:                           #define dependencies of this app
##      - db                                #dependency name (which is defined with this name 'db' in this file earlier)
##    environment:
##      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db2:3306/forte?createDatabaseIfNotExist=true?useSSL=false&serverTimezone=UTC
##      SPRING_DATASOURCE_USERNAME: root
##      SPRING_DATASOURCE_PASSWORD: FISFIS1212
##networks:
##  fort-networks:
#
#
#
#version: "3.1"
#services:
#  db:
#    image: mysql:8.0
#    ports:
#      - "3306:3306"
#    command: --default-authentication-plugin=mysql_native_password
#    environment:
#      MYSQL_DATABASE: myDb
#      MYSQL_USER: user
#      MYSQL_PASSWORD: fisfis1212
#      MYSQL_ROOT_PASSWORD: fisfis1212
#    volumes:
#      - ./dump:/docker-entrypoint-initdb.d
#      - ./conf:/etc/mysql/conf.d
#      - persistent:/var/lib/mysql
#    networks:
#      - default
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    links:
#      - db:db
#    ports:
#      - 8004:80
#    environment:
#      MYSQL_USER: user
#      MYSQL_PASSWORD: fisfis1212
#      MYSQL_ROOT_PASSWORD: fisfis1212
#volumes:
#  persistent:
